_wandb:
    value:
        cli_version: 0.23.1
        e:
            n2kdyf0e9csp9waxeshqstnm0ssxcy7p:
                args:
                    - --checkpoint
                    - /home/server5090/Desktop/M11307320/diffusion-for-ood/checkpoints/final_model.pth
                    - --ood_dataset
                    - LSUN
                    - --data_root
                    - ../datasets/
                codePath: evaluate_cifar10_ood.py
                codePathLocal: evaluate_cifar10_ood.py
                cpu_count: 20
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1966736678912"
                        used: "73531944960"
                email: dany910611@gmail.com
                executable: /home/server5090/Desktop/M11307320/diffusion-for-ood/test_ood/bin/python3
                git:
                    commit: e1c1086046f10df9914daa93880de9d53ae27f8b
                    remote: https://github.com/danyDCane/diffusion-for-ood_resnet18.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-2d1bafc4-542c-8e41-04fb-5acefde6156a
                host: server5090-System-Product-Name
                memory:
                    total: "32961908736"
                os: Linux-6.14.0-35-generic-x86_64-with-glibc2.39
                program: /home/server5090/Desktop/M11307320/diffusion-for-ood/evaluate_cifar10_ood.py
                python: CPython 3.12.3
                root: /home/server5090/Desktop/M11307320/diffusion-for-ood
                startedAt: "2026-01-12T13:29:41.079230Z"
                writerId: n2kdyf0e9csp9waxeshqstnm0ssxcy7p
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.3
            "5": 0.23.1
            "10":
                - 20
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 128
checkpoint:
    value: /home/server5090/Desktop/M11307320/diffusion-for-ood/checkpoints/final_model.pth
data_root:
    value: ../datasets/
device:
    value: cuda
diffusion_denoiser_channels:
    value: 512
num_classes:
    value: 10
num_diffusion_steps:
    value: 1000
num_eval_steps:
    value: 25
num_workers:
    value: 4
ood_dataset:
    value: LSUN
ood_eval_scores_type:
    value: eps_mse
use_wandb:
    value: true
wandb_entity:
    value: null
wandb_name:
    value: null
wandb_project:
    value: diffusion-ood-cifar10
